Game new
AgaMiasek/Modu-9 pull request #8
Opened 2017-09-11 17:46 UTC by AgaMiasek

2017-09-12 07:09 UTC, michal-bootcamp requested changes

2017-09-12 07:09 UTC, michal-bootcamp commented on 9.7/index.html
> +				New game
dla czytelnosci dalbym wieksze wciecie

2017-09-12 07:09 UTC, michal-bootcamp commented on 9.7/index.html
> +					0
dla czytelnosci dalbym wieksze wciecie

2017-09-12 07:09 UTC, michal-bootcamp commented on 9.7/index.html
> +					Player Name
dla czytelnosci dalbym wieksze wciecie

2017-09-12 07:09 UTC, michal-bootcamp commented on 9.7/index.html
> +					0
dla czytelnosci dalbym wieksze wciecie

2017-09-12 07:09 UTC, michal-bootcamp commented on 9.7/scripts.js
> +}
popraw wciecia w funkcji `playerPick` - sa wymieszane

2017-09-12 07:09 UTC, michal-bootcamp commented on 9.7/style.css
> +}
dodaj style przynajmniej na tyle, zeby bylo wiecej powietrza na stronie i elementy nie stykaly sie ze soba

2017-09-12 07:09 UTC, michal-bootcamp commented on 9.7/scripts.js
> +    }
zmien nazwe funkcji na `checkEndGame`,
dodaj wyswietlanie informacji o zwyciezcy,
dodaj zerowanie wyniku - obecnie jak uruchomie gre 'jeszcze raz' to na poczatku widze poprzedni wynik

2017-09-12 22:50 UTC, michal-bootcamp requested changes
1. Moze troche nieprecyzyjnie sie wyrazilem odnosnie zwiekszenia wciec w html. Chodzilo mi o to, ze np w takim fragmencie:
```
<button id="js-newGameButton" class="btn btn-default">
New game
</button>
```
czytelniej wyglada w ten sposob:
```
<button id="js-newGameButton" class="btn btn-default">
    New game
</button>
```
Nadal obowiazuje zasada jeden element w glab - jedno wciecie wiecej

2. Dodaj tez te informacje o zwyciezcy. Mozesz w funkcji `checkEndGame()` wyswietlic alert z informacja, kto wygral (czyli osiagnal te 10 punktow)

2017-09-14 10:04 UTC, michal-bootcamp requested changes
- [ ] [html] zmniejsz wciecie w liniach: 59-77, 80-89, 93-103
- [ ] [html] zwieksz wciecie w linii 90
Jesli jest u Ciebie problem z wizualizacja tych wciec, bo widze, ze sa wymieszane znaki tabulacji ze spacjami to w Sublime mozesz to ujednolicic `View -> Indentation -> Convert Indentation To ...`
- [ ] po wygranej gracza nie moge odpalic nowej gry
- [ ] w wyswietlaniu informacji o wygranej gracza wyswietl tez jego imie :)

2017-09-15 08:06 UTC, michal-bootcamp requested changes
ostatnie szlify :)

2017-09-15 08:06 UTC, michal-bootcamp commented on 9.7/scripts.js
> +    console.log('endGame');
console.log byl zdaje sie tylko do testowania wiec mozna juz go usunac zeby nie rzucal ciagle info do konsoli

2017-09-15 08:06 UTC, michal-bootcamp commented on 9.7/scripts.js
> + 		setGameElements();
zauwaz, ze ustawiasz to `gameState = "ended";` dla kazdego warunku ifa tak samo, wiec mozna by przeniesc to poza ifa, przed `setGameElements();`

2017-09-17 10:13 UTC, AgaMiasek commented on 9.7/scripts.js
> +        gameState = "ended";
nie mogę wyrzucić poza ify gameState, bo gra mi się rozsypuje

2017-09-17 12:26 UTC, michal-bootcamp commented on 9.7/scripts.js
> +        gameState = "ended";
o ja no przeciez racja, bo wtedy od razu by sie konczyla - sorry, moje niedopatrzenie :) wszystko smiga elegancko

2017-09-17 12:27 UTC, merged